url=https://naveenautomationlabs.com/opencart/index.php
browser=chrome
app.email=ENC(YJwQh3bE1xwpaU0LjdwpE74nceeIou/M1VE8zhwH2RQ1WcneYQ8CdWY36TFwrot3xh13DMCN)
app.password=ENC(W2Fl+z/uWJv7QeZ4p3KiQbmGwuhC2aykfd2LuMj4qxZ2VFZYf9yHFPlQhw==)